config/routes.rb
Wikiclone::Application.routes.draw do
  devise_for :users
  resources :users, only: [:update, :show]

  resources :wikis

  resources :charges, only: [:new, :create]

  get 'about' => 'welcome#about'

  root to: 'welcome#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :wikis
  has_and_belongs_to_many :wikicollaborators, class_name: 'Wiki'

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  
  def role?(base_role)
    role == base_role.to_s
  end
end

app/models/users_wikis.rb
class UsersWikis < ActiveRecord::Base
  belongs_to :users
  belongs_to :wikis
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :collaborators, class_name: 'User'
  
  extend FriendlyId

  friendly_id :title, use: [:finders, :history]

  default_scope {order('created_at DESC')}
  scope :visible_to, -> (user){user ? all : where(public: true)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end
 
  protected
 
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      name: "Wikiclone Membership",
      description: "Premium Membership for #{current_user.name}",
      amount: 50 
      # We're like the Snapchat for Wikipedia. But really, 
      # change this amount. Stripe won't charge $9 billion.
    }
  end

  def create

    @amount = params[:amount]

    # Creates a Stripe Customer object, for associating
    # with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    # Where the real magic happens
    charge = Stripe::Charge.create(
      customer: customer.id, # Note -- this is NOT the user_id in your app
      amount: @amount,
      description: "Wikiclone Membership - #{current_user.email}",
      currency: 'usd'
    )

    current_user.update_attributes(role: 'premium')

    flash[:success] = "Thanks for upgrading your account, #{current_user.email}!"
    redirect_to user_path(current_user) # or wherever

    # Stripe will send back CardErrors, with friendly messages
    # when something goes wrong.
    # This `rescue block` catches and displays those errors.
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @wikis = current_user.wikis
  end

  def update
    if current_user.update_attributes(user_params)
      flash[:notice] = "User information updated"
      redirect_to edit_user_registration_path
    else
      render "devise/registrations/edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = Wiki.visible_to(current_user)
    authorize @wikis
  end

  def show
    @wiki = Wiki.find(params[:id])

    if request.path != wiki_path(@wiki)
      redirect_to @wiki, status: :moved_permanently
    end
  end

  def new
    @wiki = Wiki.new
    @users = (current_user.blank? ? User.all : User.find(:all, :conditions => ["id != ?", current_user.id]))
    authorize @wiki
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @users = (current_user.blank? ? User.all : User.find(:all, :conditions => ["id != ?", current_user.id]))
    authorize @wiki
  end

  def create
    @wiki = current_user.wikis.build(wiki_params)
    authorize @wiki

    if @wiki.save
      redirect_to @wiki, notice: "Wiki sucessfully saved."
    else
      render :new, error: "There was an error saving your Wiki. Please try again."
    end
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.slug = nil
    authorize @wiki

    if @wiki.update_attributes(wiki_params)
      redirect_to @wiki, notice: "Wiki sucessfully saved."
    else
      render :new, error: "There was an error saving your Wiki. Please try again."
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    name = @wiki.title
    authorize @wiki

    if @wiki.destroy
      redirect_to wikis_path, notice: "\"#{name}\" sucessfully deleted."
    else
      redirect_to @wiki, error: "There was an error deleting your Wiki. Please try again."
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :public, collaborator_ids:[])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render text).html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <!-- The form doesn't pass the amount to the create action, so we have to pass it manually. -->
  <%= hidden_field_tag :amount, @stripe_btn_data[:amount] %>

  <h2>Upgrade Your Account</h2>
  <p>Upgrade your account and create private wikis. In addition, add an unlimited number of collaborators to your private wikis.</p>
  <script
    class='stripe-button'
    src="https://checkout.stripe.com/checkout.js"
    data-key="<%= @stripe_btn_data[:key] %>"
    data-image="<%= asset_path('wikiclone-logo.png') %>"
    data-name="<%= @stripe_btn_data[:name] %>"
    data-amount="<%= @stripe_btn_data[:amount] %>"
    data-description="<%= @stripe_btn_data[:description] %>" >
  </script>
<% end %>

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Wikiclone
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .container
      %ul.nav.nav-tabs
        %li= link_to "Wikiclone", root_path
        %li= link_to "About", about_path
        %li= link_to "Wikis", wikis_path
        - if current_user
          %li= link_to "My Wikis", current_user
          %li= link_to "Profile", edit_user_registration_path
          - if !current_user.role?(:premium)
            %li= link_to "Upgrade", new_charge_path

        .pull-right.user-info
          - if current_user
            Welcome back #{(current_user.name || current_user.email)}! #{link_to "Sign out", destroy_user_session_path, method: :delete}
          - else
            #{link_to "Sign In", new_user_session_path} or #{link_to "Sign Up", new_user_registration_path}
      - if flash[:notice]
        %br
        .alert.alert-success
          %button.close{type: "button", data: {dismiss: "alert"}} &times;
          = flash[:notice]
      - elsif flash[:error]
        %br
        .alert.alert-danger
          %button.close{type: "button", data: {dismiss: "alert"}} &times;
          = flash[:error]
      - elsif flash[:alert]
        %br
        .alert.alert-warning
          %button.close{type: "button", data: {dismiss: "alert"}} &times;
          = flash[:alert]
      = yield

app/views/users/show.html.haml
%h1 My Wikis
- @wikis.each do |wiki|
  .media
    .media-body
      %ul.list-inline
        %li
          %h4.media-heading= link_to wiki.title, wiki
        %li.pull-right
          = link_to "Edit wiki", edit_wiki_path(wiki), class: 'btn btn-success'
          = link_to "Delete wiki", wiki, class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure you want to delete this wiki?'}
- if policy(Wiki.new).create?
  = link_to "New wiki", new_wiki_path, class: 'btn btn-success'

app/views/welcome/about.html.haml
%h1 About Wikiclone
%p Wikiclone is a Ruby on Rails based collaboration tool that allows members to create public Markdown-based wikis. Additionally, members can purchase a premium account which allows them to add collaborators and create private wikis.
%ul
  %li Create wiki page using Markdown syntax.
  %li Create public wikis that anyone may view.
  %li Upgrade your account and create private wikis.
  %ul
    %li With a premium account you can add an unlimited number of collaborators to your private wikis.
%h2 Want to try it out?
%p If you are interested in test-driving Wikiclone login using the following cedentials:
%strong Premium Account
%ul.list-unstyled
  %li U: john@example.com
  %li P: helloworld
%strong Member Account
%ul.list-unstyled
  %li U: matthew@example.com
  %li P: helloworld
%h2 Want to see more?
%p If you are interested in or have any questions about my work, please visit my site at <a href="http://www.soriafernando.com/" target="_blank">www.soriafernando.com</a>.

app/views/welcome/index.html.haml
%br
.jumbotron
  %h1 Wikiclone
  %p Wikiclone allows users to create public and private Markdown-based wikis.
  %p #{link_to "Sign In", new_user_session_path, class: 'btn btn-primary'} or #{link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary'} today!

app/views/wikis/_form.html.haml
= form_for [wiki] do |form|
  - if wiki.errors.any?
    .alert.alert-danger
      %h4 There are #{pluralize(wiki.errors.count, "error")}
      %ul
        - wiki.errors.full_messages.each do |msg|
          %li= msg

  .col-md-6
    .form-group
      = form.label :title
      = form.text_field :title, autofocus: true, class: 'form-control', placeholder: 'Enter title'
    
    .form-group
      = form.label :body
      = form.text_area :body, rows: 20, class: 'form-control', placeholder: 'Enter body'
    
    - if policy(@wiki).premium?
      .form-group
        = form.label :public, class: 'checkbox' do
          #{form.check_box :public} Public Wiki

    .form-group
      = form.submit 'Save', class: 'btn btn-success'

  - if policy(@wiki).premium?
    .col-md-6
      %h3
        Add Collaborators to
        = wiki.title ? "#{wiki.title}" : "New Wiki" 
      %em (showing all users)
      %hr
      .form-group
        %ul.list-unstyled
          - @users.each do |user|
            %li
              = check_box_tag "wiki[collaborator_ids][]", user.id, @wiki.collaborators.include?(user)
              = user.name

app/views/wikis/edit.html.haml
%h2 Edit Wiki
.row
  .col-md-12
    .row
      = render partial: 'form', locals: {wiki: @wiki}

app/views/wikis/index.html.haml
%h1 Wikis
- @wikis.each do |wiki|
  .media
    .media-body
      %h4.media-heading= link_to wiki.title, wiki
- if policy(Wiki.new).create?
  %a.btn.btn-success{href: new_wiki_path} New wiki

app/views/wikis/new.html.haml
%h2 Create New Wiki
.row
  .col-md-12
    .row
      = render partial: 'form', locals: {wiki: @wiki}

app/views/wikis/show.html.haml
%h1= @wiki.title
%p= markdown(@wiki.body)
- if policy(@wiki).edit?
  = link_to "Edit wiki", edit_wiki_path, class: 'btn btn-success'
  = link_to "Delete wiki", @wiki, class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure you want to delete this wiki?'}